/*
HSM Service

A simple REST-API to access a Cloud-HSM

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HSM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HSM{}

// HSM struct for HSM
type HSM struct {
	Id string `json:"id"`
	DefaultKeyDomain string `json:"defaultKeyDomain"`
	KeyDomains []KeyDomainStatus `json:"keyDomains"`
	Keys []Key `json:"keys"`
}

type _HSM HSM

// NewHSM instantiates a new HSM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHSM(id string, defaultKeyDomain string, keyDomains []KeyDomainStatus, keys []Key) *HSM {
	this := HSM{}
	this.Id = id
	this.DefaultKeyDomain = defaultKeyDomain
	this.KeyDomains = keyDomains
	this.Keys = keys
	return &this
}

// NewHSMWithDefaults instantiates a new HSM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHSMWithDefaults() *HSM {
	this := HSM{}
	return &this
}

// GetId returns the Id field value
func (o *HSM) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HSM) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HSM) SetId(v string) {
	o.Id = v
}

// GetDefaultKeyDomain returns the DefaultKeyDomain field value
func (o *HSM) GetDefaultKeyDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultKeyDomain
}

// GetDefaultKeyDomainOk returns a tuple with the DefaultKeyDomain field value
// and a boolean to check if the value has been set.
func (o *HSM) GetDefaultKeyDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultKeyDomain, true
}

// SetDefaultKeyDomain sets field value
func (o *HSM) SetDefaultKeyDomain(v string) {
	o.DefaultKeyDomain = v
}

// GetKeyDomains returns the KeyDomains field value
func (o *HSM) GetKeyDomains() []KeyDomainStatus {
	if o == nil {
		var ret []KeyDomainStatus
		return ret
	}

	return o.KeyDomains
}

// GetKeyDomainsOk returns a tuple with the KeyDomains field value
// and a boolean to check if the value has been set.
func (o *HSM) GetKeyDomainsOk() ([]KeyDomainStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.KeyDomains, true
}

// SetKeyDomains sets field value
func (o *HSM) SetKeyDomains(v []KeyDomainStatus) {
	o.KeyDomains = v
}

// GetKeys returns the Keys field value
func (o *HSM) GetKeys() []Key {
	if o == nil {
		var ret []Key
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *HSM) GetKeysOk() ([]Key, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *HSM) SetKeys(v []Key) {
	o.Keys = v
}

func (o HSM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HSM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["defaultKeyDomain"] = o.DefaultKeyDomain
	toSerialize["keyDomains"] = o.KeyDomains
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *HSM) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"defaultKeyDomain",
		"keyDomains",
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHSM := _HSM{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHSM)

	if err != nil {
		return err
	}

	*o = HSM(varHSM)

	return err
}

type NullableHSM struct {
	value *HSM
	isSet bool
}

func (v NullableHSM) Get() *HSM {
	return v.value
}

func (v *NullableHSM) Set(val *HSM) {
	v.value = val
	v.isSet = true
}

func (v NullableHSM) IsSet() bool {
	return v.isSet
}

func (v *NullableHSM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHSM(val *HSM) *NullableHSM {
	return &NullableHSM{value: val, isSet: true}
}

func (v NullableHSM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHSM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


