/*
HSM Service

A simple REST-API to access a Cloud-HSM

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// KeyAlgorithm the model 'KeyAlgorithm'
type KeyAlgorithm string

// List of KeyAlgorithm
const (
	RSA_PSS KeyAlgorithm = "RSA_PSS"
	RSA_PSS_SHA1 KeyAlgorithm = "RSA_PSS_SHA1"
	RSA_PSS_SHA256 KeyAlgorithm = "RSA_PSS_SHA256"
	RSA_PSS_SHA512 KeyAlgorithm = "RSA_PSS_SHA512"
	ECDSA KeyAlgorithm = "ECDSA"
	ECDSA_SHA1 KeyAlgorithm = "ECDSA_SHA1"
	ECDSA_SHA256 KeyAlgorithm = "ECDSA_SHA256"
	ECDSA_SHA384 KeyAlgorithm = "ECDSA_SHA384"
	ECDSA_SHA512 KeyAlgorithm = "ECDSA_SHA512"
	DEFAULT_SIGN KeyAlgorithm = "DEFAULT_SIGN"
	CBC_ENC KeyAlgorithm = "CBC_ENC"
	CBC_DEC KeyAlgorithm = "CBC_DEC"
	CMAC KeyAlgorithm = "CMAC"
	WRAP KeyAlgorithm = "WRAP"
	DERIVE_SP800_56_C KeyAlgorithm = "DERIVE_SP800_56C"
)

// All allowed values of KeyAlgorithm enum
var AllowedKeyAlgorithmEnumValues = []KeyAlgorithm{
	"RSA_PSS",
	"RSA_PSS_SHA1",
	"RSA_PSS_SHA256",
	"RSA_PSS_SHA512",
	"ECDSA",
	"ECDSA_SHA1",
	"ECDSA_SHA256",
	"ECDSA_SHA384",
	"ECDSA_SHA512",
	"DEFAULT_SIGN",
	"CBC_ENC",
	"CBC_DEC",
	"CMAC",
	"WRAP",
	"DERIVE_SP800_56C",
}

func (v *KeyAlgorithm) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := KeyAlgorithm(value)
	for _, existing := range AllowedKeyAlgorithmEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid KeyAlgorithm", value)
}

// NewKeyAlgorithmFromValue returns a pointer to a valid KeyAlgorithm
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewKeyAlgorithmFromValue(v string) (*KeyAlgorithm, error) {
	ev := KeyAlgorithm(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for KeyAlgorithm: valid values are %v", v, AllowedKeyAlgorithmEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v KeyAlgorithm) IsValid() bool {
	for _, existing := range AllowedKeyAlgorithmEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to KeyAlgorithm value
func (v KeyAlgorithm) Ptr() *KeyAlgorithm {
	return &v
}

type NullableKeyAlgorithm struct {
	value *KeyAlgorithm
	isSet bool
}

func (v NullableKeyAlgorithm) Get() *KeyAlgorithm {
	return v.value
}

func (v *NullableKeyAlgorithm) Set(val *KeyAlgorithm) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyAlgorithm) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyAlgorithm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyAlgorithm(val *KeyAlgorithm) *NullableKeyAlgorithm {
	return &NullableKeyAlgorithm{value: val, isSet: true}
}

func (v NullableKeyAlgorithm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyAlgorithm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

