/*
HSM Service

A simple REST-API to access a Cloud-HSM

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KeyDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyDomain{}

// KeyDomain struct for KeyDomain
type KeyDomain struct {
	Id string `json:"id"`
	Label *string `json:"label,omitempty"`
	Hsms []string `json:"hsms"`
	Keys []Key `json:"keys"`
}

type _KeyDomain KeyDomain

// NewKeyDomain instantiates a new KeyDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyDomain(id string, hsms []string, keys []Key) *KeyDomain {
	this := KeyDomain{}
	this.Id = id
	this.Hsms = hsms
	this.Keys = keys
	return &this
}

// NewKeyDomainWithDefaults instantiates a new KeyDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyDomainWithDefaults() *KeyDomain {
	this := KeyDomain{}
	return &this
}

// GetId returns the Id field value
func (o *KeyDomain) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KeyDomain) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KeyDomain) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *KeyDomain) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyDomain) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *KeyDomain) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *KeyDomain) SetLabel(v string) {
	o.Label = &v
}

// GetHsms returns the Hsms field value
func (o *KeyDomain) GetHsms() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Hsms
}

// GetHsmsOk returns a tuple with the Hsms field value
// and a boolean to check if the value has been set.
func (o *KeyDomain) GetHsmsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hsms, true
}

// SetHsms sets field value
func (o *KeyDomain) SetHsms(v []string) {
	o.Hsms = v
}

// GetKeys returns the Keys field value
func (o *KeyDomain) GetKeys() []Key {
	if o == nil {
		var ret []Key
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *KeyDomain) GetKeysOk() ([]Key, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *KeyDomain) SetKeys(v []Key) {
	o.Keys = v
}

func (o KeyDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	toSerialize["hsms"] = o.Hsms
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *KeyDomain) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"hsms",
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyDomain := _KeyDomain{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKeyDomain)

	if err != nil {
		return err
	}

	*o = KeyDomain(varKeyDomain)

	return err
}

type NullableKeyDomain struct {
	value *KeyDomain
	isSet bool
}

func (v NullableKeyDomain) Get() *KeyDomain {
	return v.value
}

func (v *NullableKeyDomain) Set(val *KeyDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyDomain(val *KeyDomain) *NullableKeyDomain {
	return &NullableKeyDomain{value: val, isSet: true}
}

func (v NullableKeyDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


