/*
HSM Service

A simple REST-API to access a Cloud-HSM

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignatureInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignatureInput{}

// SignatureInput struct for SignatureInput
type SignatureInput struct {
	Hash string `json:"hash"`
	Algo KeyAlgorithm `json:"algo"`
}

type _SignatureInput SignatureInput

// NewSignatureInput instantiates a new SignatureInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignatureInput(hash string, algo KeyAlgorithm) *SignatureInput {
	this := SignatureInput{}
	this.Hash = hash
	this.Algo = algo
	return &this
}

// NewSignatureInputWithDefaults instantiates a new SignatureInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignatureInputWithDefaults() *SignatureInput {
	this := SignatureInput{}
	return &this
}

// GetHash returns the Hash field value
func (o *SignatureInput) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *SignatureInput) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *SignatureInput) SetHash(v string) {
	o.Hash = v
}

// GetAlgo returns the Algo field value
func (o *SignatureInput) GetAlgo() KeyAlgorithm {
	if o == nil {
		var ret KeyAlgorithm
		return ret
	}

	return o.Algo
}

// GetAlgoOk returns a tuple with the Algo field value
// and a boolean to check if the value has been set.
func (o *SignatureInput) GetAlgoOk() (*KeyAlgorithm, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Algo, true
}

// SetAlgo sets field value
func (o *SignatureInput) SetAlgo(v KeyAlgorithm) {
	o.Algo = v
}

func (o SignatureInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignatureInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hash"] = o.Hash
	toSerialize["algo"] = o.Algo
	return toSerialize, nil
}

func (o *SignatureInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hash",
		"algo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignatureInput := _SignatureInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignatureInput)

	if err != nil {
		return err
	}

	*o = SignatureInput(varSignatureInput)

	return err
}

type NullableSignatureInput struct {
	value *SignatureInput
	isSet bool
}

func (v NullableSignatureInput) Get() *SignatureInput {
	return v.value
}

func (v *NullableSignatureInput) Set(val *SignatureInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSignatureInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSignatureInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignatureInput(val *SignatureInput) *NullableSignatureInput {
	return &NullableSignatureInput{value: val, isSet: true}
}

func (v NullableSignatureInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignatureInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


