/*
HSM Service

A simple REST-API to access a Cloud-HSM

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Key type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Key{}

// Key struct for Key
type Key struct {
	Id string `json:"id"`
	Label string `json:"label"`
	Type KeyType `json:"type"`
	Size int32 `json:"size"`
	KeyUseCounter *int32 `json:"keyUseCounter,omitempty"`
	Algorithms []KeyAlgorithm `json:"algorithms,omitempty"`
	KeyDomain *string `json:"keyDomain,omitempty"`
	Cert *string `json:"cert,omitempty"`
	Pubkey *string `json:"pubkey,omitempty"`
	Hsms []string `json:"hsms,omitempty"`
}

type _Key Key

// NewKey instantiates a new Key object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKey(id string, label string, type_ KeyType, size int32) *Key {
	this := Key{}
	this.Id = id
	this.Label = label
	this.Type = type_
	this.Size = size
	return &this
}

// NewKeyWithDefaults instantiates a new Key object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyWithDefaults() *Key {
	this := Key{}
	return &this
}

// GetId returns the Id field value
func (o *Key) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Key) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Key) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *Key) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *Key) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *Key) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value
func (o *Key) GetType() KeyType {
	if o == nil {
		var ret KeyType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Key) GetTypeOk() (*KeyType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Key) SetType(v KeyType) {
	o.Type = v
}

// GetSize returns the Size field value
func (o *Key) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *Key) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *Key) SetSize(v int32) {
	o.Size = v
}

// GetKeyUseCounter returns the KeyUseCounter field value if set, zero value otherwise.
func (o *Key) GetKeyUseCounter() int32 {
	if o == nil || IsNil(o.KeyUseCounter) {
		var ret int32
		return ret
	}
	return *o.KeyUseCounter
}

// GetKeyUseCounterOk returns a tuple with the KeyUseCounter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Key) GetKeyUseCounterOk() (*int32, bool) {
	if o == nil || IsNil(o.KeyUseCounter) {
		return nil, false
	}
	return o.KeyUseCounter, true
}

// HasKeyUseCounter returns a boolean if a field has been set.
func (o *Key) HasKeyUseCounter() bool {
	if o != nil && !IsNil(o.KeyUseCounter) {
		return true
	}

	return false
}

// SetKeyUseCounter gets a reference to the given int32 and assigns it to the KeyUseCounter field.
func (o *Key) SetKeyUseCounter(v int32) {
	o.KeyUseCounter = &v
}

// GetAlgorithms returns the Algorithms field value if set, zero value otherwise.
func (o *Key) GetAlgorithms() []KeyAlgorithm {
	if o == nil || IsNil(o.Algorithms) {
		var ret []KeyAlgorithm
		return ret
	}
	return o.Algorithms
}

// GetAlgorithmsOk returns a tuple with the Algorithms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Key) GetAlgorithmsOk() ([]KeyAlgorithm, bool) {
	if o == nil || IsNil(o.Algorithms) {
		return nil, false
	}
	return o.Algorithms, true
}

// HasAlgorithms returns a boolean if a field has been set.
func (o *Key) HasAlgorithms() bool {
	if o != nil && !IsNil(o.Algorithms) {
		return true
	}

	return false
}

// SetAlgorithms gets a reference to the given []KeyAlgorithm and assigns it to the Algorithms field.
func (o *Key) SetAlgorithms(v []KeyAlgorithm) {
	o.Algorithms = v
}

// GetKeyDomain returns the KeyDomain field value if set, zero value otherwise.
func (o *Key) GetKeyDomain() string {
	if o == nil || IsNil(o.KeyDomain) {
		var ret string
		return ret
	}
	return *o.KeyDomain
}

// GetKeyDomainOk returns a tuple with the KeyDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Key) GetKeyDomainOk() (*string, bool) {
	if o == nil || IsNil(o.KeyDomain) {
		return nil, false
	}
	return o.KeyDomain, true
}

// HasKeyDomain returns a boolean if a field has been set.
func (o *Key) HasKeyDomain() bool {
	if o != nil && !IsNil(o.KeyDomain) {
		return true
	}

	return false
}

// SetKeyDomain gets a reference to the given string and assigns it to the KeyDomain field.
func (o *Key) SetKeyDomain(v string) {
	o.KeyDomain = &v
}

// GetCert returns the Cert field value if set, zero value otherwise.
func (o *Key) GetCert() string {
	if o == nil || IsNil(o.Cert) {
		var ret string
		return ret
	}
	return *o.Cert
}

// GetCertOk returns a tuple with the Cert field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Key) GetCertOk() (*string, bool) {
	if o == nil || IsNil(o.Cert) {
		return nil, false
	}
	return o.Cert, true
}

// HasCert returns a boolean if a field has been set.
func (o *Key) HasCert() bool {
	if o != nil && !IsNil(o.Cert) {
		return true
	}

	return false
}

// SetCert gets a reference to the given string and assigns it to the Cert field.
func (o *Key) SetCert(v string) {
	o.Cert = &v
}

// GetPubkey returns the Pubkey field value if set, zero value otherwise.
func (o *Key) GetPubkey() string {
	if o == nil || IsNil(o.Pubkey) {
		var ret string
		return ret
	}
	return *o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Key) GetPubkeyOk() (*string, bool) {
	if o == nil || IsNil(o.Pubkey) {
		return nil, false
	}
	return o.Pubkey, true
}

// HasPubkey returns a boolean if a field has been set.
func (o *Key) HasPubkey() bool {
	if o != nil && !IsNil(o.Pubkey) {
		return true
	}

	return false
}

// SetPubkey gets a reference to the given string and assigns it to the Pubkey field.
func (o *Key) SetPubkey(v string) {
	o.Pubkey = &v
}

// GetHsms returns the Hsms field value if set, zero value otherwise.
func (o *Key) GetHsms() []string {
	if o == nil || IsNil(o.Hsms) {
		var ret []string
		return ret
	}
	return o.Hsms
}

// GetHsmsOk returns a tuple with the Hsms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Key) GetHsmsOk() ([]string, bool) {
	if o == nil || IsNil(o.Hsms) {
		return nil, false
	}
	return o.Hsms, true
}

// HasHsms returns a boolean if a field has been set.
func (o *Key) HasHsms() bool {
	if o != nil && !IsNil(o.Hsms) {
		return true
	}

	return false
}

// SetHsms gets a reference to the given []string and assigns it to the Hsms field.
func (o *Key) SetHsms(v []string) {
	o.Hsms = v
}

func (o Key) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Key) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["type"] = o.Type
	toSerialize["size"] = o.Size
	if !IsNil(o.KeyUseCounter) {
		toSerialize["keyUseCounter"] = o.KeyUseCounter
	}
	if !IsNil(o.Algorithms) {
		toSerialize["algorithms"] = o.Algorithms
	}
	if !IsNil(o.KeyDomain) {
		toSerialize["keyDomain"] = o.KeyDomain
	}
	if !IsNil(o.Cert) {
		toSerialize["cert"] = o.Cert
	}
	if !IsNil(o.Pubkey) {
		toSerialize["pubkey"] = o.Pubkey
	}
	if !IsNil(o.Hsms) {
		toSerialize["hsms"] = o.Hsms
	}
	return toSerialize, nil
}

func (o *Key) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
		"type",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKey := _Key{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKey)

	if err != nil {
		return err
	}

	*o = Key(varKey)

	return err
}

type NullableKey struct {
	value *Key
	isSet bool
}

func (v NullableKey) Get() *Key {
	return v.value
}

func (v *NullableKey) Set(val *Key) {
	v.value = val
	v.isSet = true
}

func (v NullableKey) IsSet() bool {
	return v.isSet
}

func (v *NullableKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKey(val *Key) *NullableKey {
	return &NullableKey{value: val, isSet: true}
}

func (v NullableKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


