/*
HSM Service

A simple REST-API to access a Cloud-HSM

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KeyDomainStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyDomainStatus{}

// KeyDomainStatus struct for KeyDomainStatus
type KeyDomainStatus struct {
	Id string `json:"id"`
	Label string `json:"label"`
}

type _KeyDomainStatus KeyDomainStatus

// NewKeyDomainStatus instantiates a new KeyDomainStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyDomainStatus(id string, label string) *KeyDomainStatus {
	this := KeyDomainStatus{}
	this.Id = id
	this.Label = label
	return &this
}

// NewKeyDomainStatusWithDefaults instantiates a new KeyDomainStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyDomainStatusWithDefaults() *KeyDomainStatus {
	this := KeyDomainStatus{}
	return &this
}

// GetId returns the Id field value
func (o *KeyDomainStatus) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KeyDomainStatus) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KeyDomainStatus) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *KeyDomainStatus) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *KeyDomainStatus) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *KeyDomainStatus) SetLabel(v string) {
	o.Label = v
}

func (o KeyDomainStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyDomainStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	return toSerialize, nil
}

func (o *KeyDomainStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyDomainStatus := _KeyDomainStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKeyDomainStatus)

	if err != nil {
		return err
	}

	*o = KeyDomainStatus(varKeyDomainStatus)

	return err
}

type NullableKeyDomainStatus struct {
	value *KeyDomainStatus
	isSet bool
}

func (v NullableKeyDomainStatus) Get() *KeyDomainStatus {
	return v.value
}

func (v *NullableKeyDomainStatus) Set(val *KeyDomainStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyDomainStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyDomainStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyDomainStatus(val *KeyDomainStatus) *NullableKeyDomainStatus {
	return &NullableKeyDomainStatus{value: val, isSet: true}
}

func (v NullableKeyDomainStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyDomainStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


