/*
HSM Service

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client_test

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService GetHSM", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var hsmId string

		resp, httpRes, err := apiClient.DefaultAPI.GetHSM(context.Background(), hsmId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetHSMList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.GetHSMList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyId string

		resp, httpRes, err := apiClient.DefaultAPI.GetKey(context.Background(), keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKeyDomain", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kdId string

		resp, httpRes, err := apiClient.DefaultAPI.GetKeyDomain(context.Background(), kdId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKeyDomainList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.GetKeyDomainList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKeyForHSM", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var hsmId string
		var keyId string

		resp, httpRes, err := apiClient.DefaultAPI.GetKeyForHSM(context.Background(), hsmId, keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKeyForKeyDomain", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kdId string
		var keyId string

		resp, httpRes, err := apiClient.DefaultAPI.GetKeyForKeyDomain(context.Background(), kdId, keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKeyList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.GetKeyList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKeysForHSM", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var hsmId string

		resp, httpRes, err := apiClient.DefaultAPI.GetKeysForHSM(context.Background(), hsmId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService GetKeysForKeyDomain", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var kdId string

		resp, httpRes, err := apiClient.DefaultAPI.GetKeysForKeyDomain(context.Background(), kdId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService SignHash", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyId string

		resp, httpRes, err := apiClient.DefaultAPI.SignHash(context.Background(), keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
